AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  handleUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /handleUser
            Method: ANY
      Environment:
        Variables:
          DATABASE_DATABASE: cafeteria
          DATABASE_HOST: database-test-cafeteria.ctqsjdfmbick.ca-central-1.rds.amazonaws.com
          DATABASE_PASSWORD: infernape
          DATABASE_USER: admin
      Layers:
        - >-
          arn:aws:lambda:ca-central-1:770693421928:layer:Klayers-p311-mysql-connector-python:1
      Role: 'arn:aws:iam::231388024371:role/service-role/handleUser-role-a37lddni'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      PackageType: Zip
